# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odin.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ODIN(object):
    def setupUi(self, ODIN):
        ODIN.setObjectName("ODIN")
        ODIN.resize(797, 586)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../1.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ODIN.setWindowIcon(icon)
        ODIN.setStyleSheet("background-color: #023E8A;")
        self.centralwidget = QtWidgets.QWidget(ODIN)
        self.centralwidget.setObjectName("centralwidget")
        self.GO = QtWidgets.QPushButton(self.centralwidget)
        self.GO.setGeometry(QtCore.QRect(700, 480, 75, 51))
        self.GO.setStyleSheet("border-radius: 12px;\n"
"background-color: #0077B6;\n"
"color: white;\n"
"padding: 8px 16px;\n"
"font-weight: bold;")
        self.GO.setObjectName("GO")
        self.LINE = QtWidgets.QLineEdit(self.centralwidget)
        self.LINE.setGeometry(QtCore.QRect(30, 480, 661, 51))
        self.LINE.setStyleSheet("font: 63 10pt \"Yu Gothic UI Semibold\";\n"
"background-color: #03045E;\n"
"border: 2px solid #00B4D8;\n"
"border-radius: 10px;\n"
"padding: 6px 12px;\n"
"font-size: 14px;\n"
"color: #FFFFFF;")
        self.LINE.setText("")
        self.LINE.setObjectName("LINE")
        self.TEXT = QtWidgets.QTextEdit(self.centralwidget)
        self.TEXT.setGeometry(QtCore.QRect(30, 10, 741, 461))
        self.TEXT.setStyleSheet("background-color: #001f3f;\n"
"color: white;\n"
"font-family: \'Segoe UI\';\n"
"font-size: 14px;\n"
"border: 2px solid #00b4d8;\n"
"border-radius: 10px;\n"
"padding: 10px;")
        self.TEXT.setReadOnly(True)
        self.TEXT.setObjectName("TEXT")
        ODIN.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ODIN)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 797, 21))
        self.menubar.setObjectName("menubar")
        ODIN.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ODIN)
        self.statusbar.setObjectName("statusbar")
        ODIN.setStatusBar(self.statusbar)

        self.retranslateUi(ODIN)
        QtCore.QMetaObject.connectSlotsByName(ODIN)

    def retranslateUi(self, ODIN):
        _translate = QtCore.QCoreApplication.translate
        ODIN.setWindowTitle(_translate("ODIN", "ODIN - Optimized Digital Assistant For Internal HR"))
        self.GO.setText(_translate("ODIN", "----->"))
